//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public string Company_symbol { get; set; }
        public string Company_name { get; set; }
        public string Company_sector { get; set; }
        public string Company_type { get; set; }
        public double Company_capital { get; set; }
        public int Company_totalNbrShares { get; set; }
        public int Company_ID { get; set; }
    }
}
