//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investors
    {
        public int client_ID { get; set; }
        public string client_fullName { get; set; }
        public int client_age { get; set; }
        public int client_timeHorizon { get; set; }
        public string client_email { get; set; }
    }
}
