//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturnService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public string Return_ID { get; set; }
        public Nullable<double> Return_value { get; set; }
        public Nullable<System.DateTime> Return_estimation_date { get; set; }
    }
}
