//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizerV1.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        public string Asset_ID { get; set; }
        public Nullable<int> Asset_nbShare { get; set; }
        public string Asset_name { get; set; }
        public Nullable<System.DateTime> Asset_AQS_date { get; set; }
        public Nullable<double> Asset_shareCost { get; set; }
        public Nullable<double> Asset_currentValue { get; set; }
    }
}
