//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizerV1.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comapnies
    {
        public string Company_symbol { get; set; }
        public string Company_name { get; set; }
        public string Company_sector { get; set; }
        public string Company_type { get; set; }
        public Nullable<double> Company_capital { get; set; }
        public Nullable<int> Company_totalNbrShares { get; set; }
    }
}
