//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizerV1.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        public string Currency_symbol { get; set; }
        public string Currency_name { get; set; }
        public Nullable<double> Currency_exchange_rate { get; set; }
    }
}
