//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskService.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public string Risk_ID { get; set; }
        public string Risk_Type { get; set; }
        public float Risk_value { get; set; }
        public System.DateTime Risk_estimationDate { get; set; }
        public string Asset_ID { get; set; }
    }
}
